export enum Kind {
  alias = 'alias',
  callSignature = 'call',
  const = 'const',
  constructorImplementation = 'constructor',
  constructSignature = 'construct',
  directory = 'directory',
  enum = 'enum',
  enumMember = 'enum member',
  externalModuleName = 'external module name',
  function = 'function',
  indexSignature = 'index',
  interface = 'interface',
  keyword = 'keyword',
  let = 'let',
  localFunction = 'local function',
  localVariable = 'local var',
  memberGetAccessor = 'getter',
  memberSetAccessor = 'setter',
  memberVariable = 'property',
  method = 'method',
  module = 'module',
  parameter = 'parameter',
  primitiveType = 'primitive type',
  script = 'script',
  string = 'string',
  type = 'type',
  typeParameter = 'type parameter',
  variable = 'var',
  warning = 'warning',
}
export enum DiagCategory {
  error = 'error',
  suggestion = 'suggestion',
  warning = 'warning',
}
export enum KindModifiers {
  color = 'color',
  depreacted = 'deprecated',
  dtsFile = '.d.ts',
  jsFile = '.js',
  jsonFile = '.json',
  jsxFile = '.jsx',
  optional = 'optional',
  tsFile = '.ts',
  tsxFile = '.tsx',
}
export enum DisplayPartKind {
  functionName = 'functionName',
  methodName = 'methodName',
  parameterName = 'parameterName',
  propertyName = 'propertyName',
  punctuation = 'punctuation',
  text = 'text',
}
export enum EventName {
  beginInstallTypes = 'beginInstallTypes',
  configFileDiag = 'configFileDiag',
  endInstallTypes = 'endInstallTypes',
  projectLangServiceState = 'projectLangServiceState',
  projectLoadingFinish = 'projectLoadingFinish',
  projectLoadingStart = 'projectLoadingStart',
  projectsUpdatedInBackground = 'projectsUpdatedInBackground',
  semanticDiag = 'semanticDiag',
  suggestionDiag = 'suggestionDiag',
  surveyReady = 'surveyReady',
  syntaxDiag = 'syntaxDiag',
  telemetry = 'telemetry',
  typesInstallerInitializationFailed = 'typesInstallerInitializationFailed',
}
fileExtensionKindModifiers = [KindModifiers.dtsFile, KindModifiers.tsFile, KindModifiers.tsxFile, KindModifiers.jsFile, KindModifiers.jsxFile, KindModifiers.jsonFile];
